#!/bin/sh

set -o errexit
set -o nounset

PYTHONPATH="$(dirname "${0}")/lib:$(dirname "${0}")/scripts:${PYTHONPATH-}"
export PYTHONPATH
# make a last-ditch effort to set CHUTNEY_PATH based on this script's location
if ! test "${CHUTNEY_PATH+y}"
then
    CHUTNEY_PATH=$(dirname "$0")
    export CHUTNEY_PATH
fi

python_ok ()
{
    checkpy="$1"
    test -f "${checkpy}" && \
	test -x "${checkpy}" && \
	"${checkpy}" -c 'import sys;sys.exit(sys.version_info[0]<3)'
}

binaries="python3 python"

if ! test "${PYTHON+y}"
then
    saved_IFS="${IFS}"
    for binary in ${binaries}
    do
        IFS=":"
        for directory in ${PATH}
        do
            case "${directory}" in
                "") directory="./"
                    ;;
                */)
                    ;;
                *) directory="${directory}/"
                    ;;
            esac
            abs_path="${directory}${binary}"
            if python_ok "${abs_path}"
            then
                PYTHON="${abs_path}"
                break
            fi
        done

        if test "${PYTHON+y}"
        then
            break
        fi
    done
    IFS="${saved_IFS}"
else
    if ! python_ok "$(command -v "${PYTHON}")"
    then
	echo "Python in \$PYTHON envvar (\"$PYTHON\") is not present, or is not python 3." >&2
	exit 1
    fi
fi

if ! test "${PYTHON+y}"
then
    printf "No compatible Python version found.\n" >&2
    printf "Is python 3 installed and in your PATH?\n" >&2
    exit 1
fi

printf "\nLaunching chutney using %s\n" "$("${PYTHON}" --version 2>&1)"
"${PYTHON}" -m chutney.TorNet "${@}"
